openapi: 3.0.3
info:
  title: instances
  version: '1.0'
  description: Instances Docs Here
paths:
  '/instances/{worldId}:{instanceId}':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    get:
      summary: Get Instance
      tags:
        - instances
      operationId: getInstance
      security:
        - apiKeyCookie: []
          authCookie: []
      description: |-
        Returns an instance. Please read [Instances Tutorial](https://vrchatapi.github.io/tutorials/instances/) for more information on Instances.

        If an invalid instanceId is provided, this endpoint will simply return "null"!
      x-codeSamples:
        $ref: '../codeSamples/instances.yaml#/~1intances~1{worldId}:{instanceId}/get'
      responses:
        '200':
          $ref: ../responses/instances/InstanceResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
  '/instances/{worldId}:{instanceId}/shortName':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    get:
      summary: Get Instance Short Name
      tags:
        - instances
      operationId: getShortName
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Returns an instance short name.
      x-codeSamples:
        $ref: '../codeSamples/instances.yaml#/~1instance~1{worldId}:{instanceId}~1shortName/get'
      responses:
        '200':
          $ref: ../responses/instances/InstanceShortNameResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
  '/instances/{worldId}:{instanceId}/invite':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    post:
      summary: Send Self Invite
      tags:
        - instances
      operationId: sendSelfInvite
      security:
        - apiKeyCookie: []
          authCookie: []
      description: Sends an invite to the instance to yourself.
      x-codeSamples:
        $ref: '../codeSamples/instances.yaml#/~1instance~1{worldId}:{instanceId}~1invite/post'
      responses:
        '200':
          $ref: ../responses/instances/InstanceSelfInviteSuccess.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
  '/instances/s/{shortname}':
    get:
      summary: Get Instance By Short Name
      tags:
        - instances
      responses:
        '200':
          $ref: ../responses/instances/InstanceResponse.yaml
        '401':
          $ref: ../responses/MissingCredentialsError.yaml
        '404':
          $ref: ../responses/instances/InstanceNotFoundError.yaml
      operationId: getInstanceByShortName
      security:
        - apiKeyCookie: []
          authCookie: []
      description: 'Returns an instance. Please read [Instances Tutorial](https://vrchatapi.github.io/tutorials/instances/) for more information on Instances.'
    parameters:
      - schema:
          type: string
        name: shortname
        in: path
        required: true
  '/invite/myself/to/{worldid}:{instanceid}':
    parameters:
      - $ref: ../parameters.yaml#/worldId
      - $ref: ../parameters.yaml#/instanceId
    post:
      summary: ''
      operationId: inviteMyselfTo
      security:
        - apiKeyCookie: []
          authCookie: []
      responses:
        '200':
          $ref: ../responses/notifications/NotificationResponse.yaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                shortName:
                  type: string
                  description: Short Name of the Instance; can be retrieved from the Get Instance Short Name endpoint.
              required:
                - shortName
      description: Sends self an invite to an instance
tags:
  $ref: ../tags.yaml
components:
  securitySchemes:
    $ref: ../securitySchemes.yaml
