on: [push, pull_request]
name: OpenAPI Specification CI

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint OpenAPI specification
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v12-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v12
      - name: Install Dependencies
        run: npm install
      - name: Run Spectral linting
        run: npm run lint

  bundle:
    runs-on: ubuntu-latest
    name: Bundle and Upload OpenAPI specification
    steps:
      - uses: actions/checkout@v2

      - name: Bundle OpenAPI Specification 📦
        uses: hilary/openapi-cli-bundle-action@v0.0.2
        with:
          base-spec: openapi/openapi.yaml
          bundled-spec: dist/openapi.yaml

      - name: Upload Bundled Specification as Artifact 📤
        uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: dist/openapi.yaml

      - name: Disable Jekyll for Github Pages
        run: sudo touch dist/.nojekyll; sudo touch dist/index.html
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy Bundle to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: dist