name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/openapi.yaml"
        bodyFile: "release-body.md"
        token: ${{ secrets.GITHUB_TOKEN }}